# Base de datos local simulada
db_hoteles = [
  {
    "id_hotel": 101,
    "nombre": "Boutique Luna de Plata",
    "ubicacion": "Guanajuato, GTO",
    "precio_noche_mxn": 2500.0,
    "rate_calificacion": 4.8,
    "pet_friendly": False,
    "romantico": True,
    "apto_ninos": False,
    "tipo_alojamiento": "Boutique",
    "amenidades": "Wi-Fi, Terraza, Vino de cortesía",
    "vibra_estilo": "Íntimo, Histórico",
    "descripcion_ia": "Hotel boutique colonial ideal para escapadas en pareja, sin ruido y muy céntrico.",
    "url_imagen": "https://picsum.photos/seed/hotel101/800/600"
  },
  {
    "id_hotel": 102,
    "nombre": "Resort Sol y Arena",
    "ubicacion": "Cancún, QROO",
    "precio_noche_mxn": 4500.0,
    "rate_calificacion": 4.5,
    "pet_friendly": True,
    "romantico": True,
    "apto_ninos": True,
    "tipo_alojamiento": "Resort All-Inclusive",
    "amenidades": "Piscina, Playa privada, Spa, Kids Club",
    "vibra_estilo": "Divertido, Familiar, Relajante",
    "descripcion_ia": "Resort enorme con actividades para todas las edades. Excelente para familias con mascotas.",
    "url_imagen": "https://picsum.photos/seed/hotel102/800/600"
  },
  {
    "id_hotel": 103,
    "nombre": "Cabañas del Bosque",
    "ubicacion": "Valle de Bravo, MEX",
    "precio_noche_mxn": 1800.0,
    "rate_calificacion": 4.7,
    "pet_friendly": True,
    "romantico": True,
    "apto_ninos": True,
    "tipo_alojamiento": "Cabaña",
    "amenidades": "Chimenea, Asador, Bosque",
    "vibra_estilo": "Rústico, Naturaleza",
    "descripcion_ia": "Cabañas de madera rodeadas de pinos. Perfecto para desconectarse y llevar a la familia y perros.",
    "url_imagen": "https://picsum.photos/seed/hotel103/800/600"
  },
  {
    "id_hotel": 104,
    "nombre": "Torre Ejecutiva Reforma",
    "ubicacion": "CDMX",
    "precio_noche_mxn": 3200.0,
    "rate_calificacion": 4.6,
    "pet_friendly": False,
    "romantico": False,
    "apto_ninos": True,
    "tipo_alojamiento": "Business / Urbano",
    "amenidades": "Gimnasio, Centro de negocios, Restaurante 24h",
    "vibra_estilo": "Moderno, Práctico",
    "descripcion_ia": "Hotel de negocios en el corazón de la ciudad. Rápido acceso a oficinas y museos.",
    "url_imagen": "https://picsum.photos/seed/hotel104/800/600"
  },
  {
    "id_hotel": 105,
    "nombre": "Hostal Mochilero Maya",
    "ubicacion": "Tulum, QROO",
    "precio_noche_mxn": 600.0,
    "rate_calificacion": 4.2,
    "pet_friendly": False,
    "romantico": False,
    "apto_ninos": False,
    "tipo_alojamiento": "Hostal",
    "amenidades": "Cocina compartida, Renta de bicis, Bar",
    "vibra_estilo": "Social, Económico",
    "descripcion_ia": "Hostal vibrante con mucha fiesta, ideal para viajeros solos buscando conocer gente.",
    "url_imagen": "https://picsum.photos/seed/hotel105/800/600"
  },
  {
    "id_hotel": 106,
    "nombre": "Hacienda San Miguel",
    "ubicacion": "Mérida, YUC",
    "precio_noche_mxn": 3800.0,
    "rate_calificacion": 4.9,
    "pet_friendly": True,
    "romantico": True,
    "apto_ninos": True,
    "tipo_alojamiento": "Hacienda / Lujo",
    "amenidades": "Piscina, Restaurante gourmet, Jardines",
    "vibra_estilo": "Lujoso, Cultural",
    "descripcion_ia": "Una hacienda henequenera restaurada. Ofrece una experiencia de lujo inmersiva en la cultura maya.",
    "url_imagen": "https://picsum.photos/seed/hotel106/800/600"
  },
  {
    "id_hotel": 107,
    "nombre": "Playa Escondida Only Adults",
    "ubicacion": "Puerto Escondido, OAX",
    "precio_noche_mxn": 2100.0,
    "rate_calificacion": 4.4,
    "pet_friendly": False,
    "romantico": True,
    "apto_ninos": False,
    "tipo_alojamiento": "Solo Adultos",
    "amenidades": "Playa, Bar en piscina, Clases de surf",
    "vibra_estilo": "Relajado, Romántico",
    "descripcion_ia": "Exclusivo para adultos. Excelente ambiente de playa y atardeceres espectaculares.",
    "url_imagen": "https://picsum.photos/seed/hotel107/800/600"
  },
  {
    "id_hotel": 108,
    "nombre": "Eco-Retiro Tepoz",
    "ubicacion": "Tepoztlán, MOR",
    "precio_noche_mxn": 1500.0,
    "rate_calificacion": 4.6,
    "pet_friendly": True,
    "romantico": True,
    "apto_ninos": False,
    "tipo_alojamiento": "Ecológico / Wellness",
    "amenidades": "Temazcal, Yoga, Comida vegana",
    "vibra_estilo": "Espiritual, Sanador",
    "descripcion_ia": "Retiro ecológico enfocado en el bienestar. Ideal para meditar y relajar la mente.",
    "url_imagen": "https://picsum.photos/seed/hotel108/800/600"
  },
  {
    "id_hotel": 109,
    "nombre": "Gran Plaza Centro",
    "ubicacion": "Monterrey, NL",
    "precio_noche_mxn": 2900.0,
    "rate_calificacion": 4.5,
    "pet_friendly": False,
    "romantico": False,
    "apto_ninos": True,
    "tipo_alojamiento": "Urbano",
    "amenidades": "Piscina techada, Wi-Fi rápido, Estacionamiento",
    "vibra_estilo": "Corporativo, Céntrico",
    "descripcion_ia": "A pocos pasos de la Macroplaza. Conveniente para turismo de compras y negocios.",
    "url_imagen": "https://picsum.photos/seed/hotel109/800/600"
  },
  {
    "id_hotel": 110,
    "nombre": "Villas del Mar Lujo",
    "ubicacion": "Los Cabos, BCS",
    "precio_noche_mxn": 8500.0,
    "rate_calificacion": 4.9,
    "pet_friendly": True,
    "romantico": True,
    "apto_ninos": True,
    "tipo_alojamiento": "Lujo / Villas",
    "amenidades": "Chef privado, Piscina infinita, Campo de Golf",
    "vibra_estilo": "Exclusivo, Privado",
    "descripcion_ia": "Villas privadas de ultra lujo. Ideal para lunas de miel o vacaciones familiares premium.",
    "url_imagen": "https://picsum.photos/seed/hotel110/800/600"
  },
  {
    "id_hotel": 111,
    "nombre": "Casa de los Patios",
    "ubicacion": "Oaxaca, OAX",
    "precio_noche_mxn": 1200.0,
    "rate_calificacion": 4.7,
    "pet_friendly": False,
    "romantico": True,
    "apto_ninos": True,
    "tipo_alojamiento": "Boutique / Histórico",
    "amenidades": "Desayuno tradicional, Galería de arte, Patio central",
    "vibra_estilo": "Bohemio, Tradicional",
    "descripcion_ia": "Antigua casona con patios llenos de flores y arte local. Perfecto para vivir la tradición oaxaqueña.",
    "url_imagen": "https://picsum.photos/seed/hotel111/800/600"
  },
  {
    "id_hotel": 112,
    "nombre": "Glamping Estelar",
    "ubicacion": "Valle de Guadalupe, BC",
    "precio_noche_mxn": 4200.0,
    "rate_calificacion": 4.8,
    "pet_friendly": True,
    "romantico": True,
    "apto_ninos": False,
    "tipo_alojamiento": "Glamping",
    "amenidades": "Cata de vinos, Telescopio, Fogata",
    "vibra_estilo": "Aventurero, Romántico",
    "descripcion_ia": "Domos transparentes en medio de los viñedos para dormir bajo las estrellas con todas las comodidades.",
    "url_imagen": "https://picsum.photos/seed/hotel112/800/600"
  },
  {
    "id_hotel": 113,
    "nombre": "Ejecutivo Express",
    "ubicacion": "Guadalajara, JAL",
    "precio_noche_mxn": 1400.0,
    "rate_calificacion": 4.3,
    "pet_friendly": False,
    "romantico": False,
    "apto_ninos": False,
    "tipo_alojamiento": "Business / Express",
    "amenidades": "Desayuno exprés, Wi-Fi alta velocidad, Sala de juntas",
    "vibra_estilo": "Rápido, Eficiente",
    "descripcion_ia": "Ideal para viajes de trabajo cortos. Check-in rápido y excelente conexión a internet.",
    "url_imagen": "https://picsum.photos/seed/hotel113/800/600"
  },
  {
    "id_hotel": 114,
    "nombre": "Cabañas La Cascada",
    "ubicacion": "Mazamitla, JAL",
    "precio_noche_mxn": 2200.0,
    "rate_calificacion": 4.6,
    "pet_friendly": True,
    "romantico": True,
    "apto_ninos": True,
    "tipo_alojamiento": "Cabaña",
    "amenidades": "Jacuzzi, Terraza, Cerca de cascada",
    "vibra_estilo": "Familiar, Naturaleza",
    "descripcion_ia": "Acogedoras cabañas tipo alpino rodeadas de bosque y rutas de senderismo con vistas increíbles.",
    "url_imagen": "https://picsum.photos/seed/hotel114/800/600"
  },
  {
    "id_hotel": 115,
    "nombre": "Resort Paraíso Esmeralda",
    "ubicacion": "Playa del Carmen, QROO",
    "precio_noche_mxn": 5500.0,
    "rate_calificacion": 4.7,
    "pet_friendly": False,
    "romantico": True,
    "apto_ninos": True,
    "tipo_alojamiento": "Resort Lujo",
    "amenidades": "Cenote privado, 5 Restaurantes, Club de Playa",
    "vibra_estilo": "Tropical, Exclusivo",
    "descripcion_ia": "Un paraíso tropical con servicio de primera clase, rodeado de selva y acceso directo al Mar Caribe.",
    "url_imagen": "https://picsum.photos/seed/hotel115/800/600"
  },
  {
    "id_hotel": 116,
    "nombre": "Hotel Histórico Zócalo",
    "ubicacion": "Puebla, PUE",
    "precio_noche_mxn": 1750.0,
    "rate_calificacion": 4.5,
    "pet_friendly": False,
    "romantico": True,
    "apto_ninos": True,
    "tipo_alojamiento": "Urbano / Histórico",
    "amenidades": "Restaurante con vista, Arquitectura virreinal, Tours a pie",
    "vibra_estilo": "Cultural, Céntrico",
    "descripcion_ia": "Ubicado frente a la catedral, este hotel es perfecto para quienes desean explorar la gastronomía y arquitectura poblana.",
    "url_imagen": "https://picsum.photos/seed/hotel116/800/600"
  },
  {
    "id_hotel": 117,
    "nombre": "Surf & Chill Hostal",
    "ubicacion": "Sayulita, NAY",
    "precio_noche_mxn": 850.0,
    "rate_calificacion": 4.4,
    "pet_friendly": True,
    "romantico": False,
    "apto_ninos": False,
    "tipo_alojamiento": "Hostal",
    "amenidades": "Alquiler de tablas, Bar en azotea, Clases de yoga",
    "vibra_estilo": "Relajado, Juvenil",
    "descripcion_ia": "El punto de encuentro ideal para surfistas y mochileros. Ambiente relajado con hamacas y buena música.",
    "url_imagen": "https://picsum.photos/seed/hotel117/800/600"
  },
  {
    "id_hotel": 118,
    "nombre": "Termales del Sur",
    "ubicacion": "Cuernavaca, MOR",
    "precio_noche_mxn": 2600.0,
    "rate_calificacion": 4.6,
    "pet_friendly": False,
    "romantico": True,
    "apto_ninos": True,
    "tipo_alojamiento": "Spa / Resort",
    "amenidades": "Aguas termales, Masajes, Jardines botánicos",
    "vibra_estilo": "Relajante, Sanador",
    "descripcion_ia": "Conocido por su eterna primavera, este resort ofrece piscinas de aguas termales y un spa de clase mundial.",
    "url_imagen": "https://picsum.photos/seed/hotel118/800/600"
  },
  {
    "id_hotel": 119,
    "nombre": "Refugio Nevado",
    "ubicacion": "Toluca, MEX",
    "precio_noche_mxn": 1300.0,
    "rate_calificacion": 4.2,
    "pet_friendly": True,
    "romantico": True,
    "apto_ninos": True,
    "tipo_alojamiento": "Cabaña",
    "amenidades": "Calefacción, Guías de montaña, Restaurante",
    "vibra_estilo": "Aventurero, Frío",
    "descripcion_ia": "A las faldas del Nevado de Toluca, es el refugio ideal para alpinistas y amantes de los climas fríos.",
    "url_imagen": "https://picsum.photos/seed/hotel119/800/600"
  },
  {
    "id_hotel": 120,
    "nombre": "Suites Panorámicas",
    "ubicacion": "Querétaro, QRO",
    "precio_noche_mxn": 3100.0,
    "rate_calificacion": 4.8,
    "pet_friendly": False,
    "romantico": True,
    "apto_ninos": False,
    "tipo_alojamiento": "Boutique / Suites",
    "amenidades": "Terraza privada, Tina de hidromasaje, Room service 24h",
    "vibra_estilo": "Lujoso, Exclusivo",
    "descripcion_ia": "Suites de lujo con vistas panorámicas a los acueductos. Diseño impecable y atención al detalle inmejorable.",
    "url_imagen": "https://picsum.photos/seed/hotel120/800/600"
  }
]

def buscar_en_db(destino: str, comodidades_requeridas: list[str] = [], precio_maximo: float = 9999.0) -> list[dict]:
    """
    Busca hoteles en la base de datos local. Gemini usará esta herramienta.
    """
    resultados = []
    for hotel in db_hoteles:
        if hotel["ubicacion"].lower() == destino.lower() and hotel["precio"] <= precio_maximo:
            # Verifica si tiene al menos una de las comodidades requeridas
            if not comodidades_requeridas or any(c in hotel["comodidades"] for c in comodidades_requeridas):
                resultados.append(hotel)
    return resultados